config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :groups, only: %i[create new index destroy] do
    resources :transfers, only: %i[create new index destroy]
  end
  devise_scope :user do
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    user ||= User.new # guest user (not logged in)

    if user.role == 'admin'
      can :manage, :all # admin can do everything
    else
      can :read, :all # everyone can read everything
      can :create, Group # everyone can create groups
      can :create, Transfer # everyone can create transfer
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :transfers

  validates :name, presence: true
  validates :icon, presence: true
  def self.created_by_current_user(current_user)
    where(user_id: current_user.id).order(created_at: :desc)
  end
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0,
                                                     message: 'must be an integer greater than or equal to zero.' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :transfers, foreign_key: 'author_id'
  has_many :groups

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      redirect_to groups_path, notice: 'Category was successfully created'
    else
      render :new, alert: "Couldn't create Category for user"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to user_recipes_path, notice: 'Category was successfully deleted'
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :authenticate_user!

  def index
    @transfers = Transfer.joins(:groups).where(groups: { id: params[:group_id] }).order(created_at: :desc)
    @group = Group.find(params[:group_id])
  end

  def new
    @transfer = Transfer.new
    @groups = Group.created_by_current_user(current_user)
  end

  def create
    params = transfer_params
    @transfer = Transfer.new(name: params[:name], amount: params[:amount])
    @transfer.author = current_user
    @group_ids = params[:group_ids]
    @group_ids.each do |id|
      @group = Group.find(id) unless id == ''
      @transfer.groups.push(@group) unless @group.nil?
    end
    if @transfer.save
      redirect_to "/groups/#{@transfer.groups.first.id}/transfers", notice: 'transfer was successfully added'
    else
      render :new, alert: "Couldn't add food to transfer"
    end
  end

  def destroy
    @user = current_user
    @transfer = Transfer.find(params[:id])
    @transfer.destroy

    redirect_to "/groups/#{@group.id}/transfers", notice: 'transfer was successfully deleted'
  end

  def transfer_params
    params.require(:transfer).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<%= render 'groups/shared/header' %>
<h1 class="categori">Categories</h1>
<section>
  <% @groups.each do |group| %>
    <section class="category_section">
      <div class="category">
        <div class="expenses">
          <img class="icon_img" src="<%= group.icon %>" alt="icon" />
          <p class="category_name"><%= link_to group.name, group_transfers_path(group) %></p>
        </div>
        <p>$<%= group.transfers.inject(0) { |sum, e| sum += e.amount } %></p>
      </div>
    </section>
  <% end %>

  <div class="category_btn_container"><button class="new_category"><%= link_to "new category", new_group_path %></button><div>
</section>

app/views/groups/new.html.erb
<section>
  <%= render 'groups/shared/header' %>
  <%= render 'groups/shared/form' %>
</section>

app/views/groups/shared/_form.html.erb
<div><button class="save"><%= link_to "back", groups_path  %></button></div>
<div class="category_form">
    <%= form_with(model: @group, url: groups_path, method: :post) do |form| %>
      <div class="form-group">
      <%= form.label :icon, class: "label" %>
      <%= form.text_field :icon, class: 'form-field', placeholder: "Image URL", autocomplete: "name" %>
      </div>
    
    <div class="form-group">
      <%= form.label :name, class: "label" %>
      <%= form.text_field :name, class: 'form-field', autocomplete: "name" %>
    </div>
    
    <div class="category_btn_container"><%= form.submit 'save', class: 'new_category' %></div>
    <% end %>
</div>

app/views/groups/shared/_header.html.erb
<div class="header bg-[#3774BD] py-4">
  <h1 class="text-[#fff]">Transactions</h1>
  <p class="text-[#fff]"><%= current_user.name %></p>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
</div>

app/views/home/index.html.erb
<div class="splash">
    <div>
        <h1 class="title">Budget App</h1>
        <div class="splash_buttons">
            <button class="new_category"><%= link_to 'Signup', new_user_registration_path, class: 'nav-sign-up-btn' %></button>
            <button class="new_category"><%= link_to 'Sign in',  new_user_session_path, class: 'nav-sign-in-btn' %></button>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  </body>
</html>

app/views/transfers/_form.html.erb
<button class="save"><%= link_to "back", groups_path  %></button>

<div class="category_form">
<%= form_with(model: @transfer, url: group_transfers_path, method: :post) do |form| %>
<div class="form-group">
  <%= form.label :name, class: "label" %>
  <%= form.text_field :name, class: 'form-field', autocomplete: "name" %>
</div>

<div class="form-group">
<%= form.label :amount, class: "label" %>
<%= form.number_field :amount, class: 'form-field' %>
</div>

<% if @groups %>
  <div class="groups">
      <%= form.label :groups, class: "label" %>
      <%= form.collection_check_boxes(:group_ids, @groups, :id, :name) do |b| %>
          <div class="checkbox">
          <%= b.check_box + b.label %>
          </div>
      <% end %>
  <div>
<% end %>

<div class="category_btn_container"><%= form.submit 'Create expense', class: 'new_category' %></div>
<% end %>
</div>

app/views/transfers/index.html.erb
<section>
  <%= render 'groups/shared/header' %>

  <button class="save"><%= link_to "back", groups_path  %></button>
  <div class="total_expenses">
    <h1><%= @group.name %></h1>
    <span>Total expenses </span><span class="green">$<%= @transfers.inject(0) { |sum, e| sum += e.amount } %></span>
  </div>
  <div><img class="transfer_icon" src="<%= @group.icon %>" alt="icon" /></div>
  
  <% @transfers.each do |transfer| %>
    <div class="total_expenses">
      <p><%= transfer.name %></p>
      <p>amount: <span class="green">$<%= transfer.amount %></span></p>
    </div>
  <% end %>
  
  <div class="category_btn_container"><button class="new_category"><%= link_to "new expense", new_group_transfer_path %></button><div>
</section>

app/views/transfers/new.html.erb
<section>
  <%= render 'groups/shared/header' %>
  <%= render 'form' %>
</section>

app/views/users/index.html.erb
<h1>hello world</h1>